---
- name: Cisco Banner
  hosts: ios
  gather_facts: false

  tasks:
  - name: Add Banner
    ios_banner:
      banner: login
      text: |
        Nicolas Cage is the
        Tiger King
      state: present
