---
- name: Create a Proxmox VM
  hosts: prox2
  gather_facts: false

  vars:
    proxmox_api_user: 'root@pam!ansible'
    proxmox_api_password: '0c4a49ce-de8d-40cd-9af5-31218f894c0f'
    proxmox_api_host: 10.0.200.11
    proxmox_api_port: '8006'
    proxmox_vm_name: 'ansible-deploy'
    proxmox_vm_template: 'ubuntu-cloud'
    proxmox_vm_node: 'prox2'
    proxmox_vm_cores: 2
    proxmox_vm_memory: 4096
    proxmox_vm_disk_size: 20G

  tasks:
    - name: Start creating vm
      proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        api_port: "{{ proxmox_api_port }}"
        vmid: 1100 # ID for the new VM
        node: "{{ proxmox_vm_node }}"
        name: "{{ proxmox_vm_name }}"
        cores: "{{ proxmox_vm_cores }}"
        memory: "{{ proxmox_vm_memory }}"
        disks:
        - size: "{{ proxmox_vm_disk_size }}"
        storage: ceph # Storage pool for the disk
        template: "{{ proxmox_vm_template }}"
        state: present